
services:
  kuke-board-mysql:
    image: mysql:8.0.38
    container_name: kuke-board-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kuke_board

    volumes:
      - ./mysql:/var/lib/mysql
    ports:
        - "3306:3306"
volumes:
    mysql:
